allinurl/goaccess

src/commons.c, src/gdashboard.c, src/output.c, src/parser.c, src/tcabinet.c, src/ui.c
[The function "free"](http://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") is documented in the way that no action shall occur for a passed null pointer.
Redundant safety checks can be avoided.
=> Delete unnecessary checks before calls of the function "free".

configure.ac
This patch outputs ```$LDFLAGS``` with ```$LIBS``` to detect if goaccess is properly linked.
=> Refine configure output

Makefile.am
I haven't found math.h #include in sources, probably a cleanup mess from the past?
Also if you want to use libm, please use configure.ac:
```
AC_CHECK_LIB(m, THE_MATH_FUNCTION_GOACCESS_USES_BUT_NOT_SHOWN_IN_GIT_SO_I_DONT_KNOW_YET)
```
=> Drop math library linking flag

src/commons.h, src/parser.c, src/util.c
I added the missing HTTP methods and HTTP Status fron the HTTP Extension for Webdav (RFC 2518 and RFC 3253)
Please check and  merge, 
Thanks
=> Add WebDav HTTP Methods and HTTP Status from RFC 2518 and RFC 3253

config/goaccess.conf
Virtualmin uses a format that is not NCSA Standard.
=> Virtualmin Support Update goaccess.conf

configure.ac
When ncurses is built with --with-termlib=tinfo option then there are two libraries - libtinfo (which contains terminal related functions) and libncurses (rest). We should correctly link against libtinfo in such case.
=> Correctly link against libtinfo

src/tcbtdb.c
... and fix improper snprintf buffer size broken by
703d69b6478fe2fad2c1c78e746cc766bc13673c
=> Fixed improper handling of snprintf return value

config/goaccess.conf
sadly, I found that rule useful.
=> adds .less files to static files list

resources/js/app.js
If a panel does not exist in AppData but is set in AppUIData, JavaScript will throw a fatal error.
For example this happens if no virtual hosts are parsed.
=> Fix: bug if panel does not exist

src/goaccess.c
`[F1]Help` :arrow_forward: `[F1] Help`
=> Add a space after [F1]

src/parser.c
Hi,
I am trying to parse the following format log by goaccess.
```
log_format %s\t%d %t\t%D\t%U\t%q
```
But error happened when query string is empty.
```
```
Please allow empty query string.
=> Allow empty query string

src/browsers.c
For example, gsutil is based on Python but not a crawler.
=> browser: classify google cloud clients

resources/js/app.js
Before this fix, if one specifed `--ws-url=wss://mydomain:443/wsproxy`, the implementation would change that to `wss://mydomain:443/wsproxy:7890` (obviously wrong). My use case is nginx proxying incoming WebSocket requests to the goaccess process ([nginx instructions](https://www.nginx.com/blog/websocket-nginx/)) - that way I don't need to open up the goaccess port in the firewall, and can use nginx's HTTPS support, and can use HTTP between nginx and goaccess (SSL feature not needed here).
The change makes the regex less strict, in order to allow URL paths like `/wsproxy`, while still detecting correctly whether a port was specified or not.
=> Allow path other than "/" in web socket URL

src/settings.c
Use bucket name as virtualhost for Amazon S3.
This isn't as valuable as the request's virtualhost, but is still useful when analyzing aggregated logs.
[S3 logs](http://docs.aws.amazon.com/AmazonS3/latest/dev/LogFormat.html) unfortunately do not include virtualhost.
I also removed the whitespace padding before the comment to follow the pattern set by the `Cloud Storage` line.
=> Use bucket name as virtualhost for Amazon S3

src/tcbtdb.c
Just a small change, but it took me quite a while to figure out, why my real time html wasn't updated any more. The reason turned out to be a wrong setting for db-path: A file instead of a directory. Goaccess started without complaining, could even read the database, but not update it. So I wrote this little 'never trust in users input'-patch.
=> Added sanity check for db-path config variable

src/browsers.c
Both the Yandex and Baidu spider are not recognized by goaccess. I've also removed IstellaBot (it was in the list twice) and added a few more. Fwiw; here is the full UA of the changed entries based on my 100M access-log (I've only looked at 50K+ entries):
* Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)
* Mozilla/5.0 (compatible; Linux x86_64; Mail.RU_Bot/2.0; +http://go.mail.ru/help/robots)
* Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)
* Blackboard Safeassign
* Mozilla/5.0 CommonCrawler Node Z2NYVDPKTTRAML5M6OVRFXUNE6*.cdn0.common.crawl.zone
* Mozilla/5.0 CommonCrawler Node Z2ATPLMYHHDOIEQKOCAV23Q5I6I4*.cdn0.common.crawl.zone
* Mozilla/5.0 CommonCrawler Node Z22ZZPFPIX4GK3DGQ5NF3BE6NOO*.cdn0.common.crawl.zone
* Mozilla/5.0 …
=> Update crawlers, fix Yandex/Baidu + add some more

Dockerfile, Dockerfile_src/init.sh
When trying to play with the docker image, I was running into some errors that wouldn't allow me to step into the container.  These seemed to be because the base image is alpine, and alpine does not have bash.  I also updated the Dockerfile to use the array syntax, which from my reading seems to be the better option: https://www.ctl.io/developers/blog/post/dockerfile-entrypoint-vs-cmd/
Below is what I was using, with the added --entrypoint to get past the error out on the init.sh script that was thrown by the ENTRYPOINT not specifying to use sh.
```
git clone https://github.com/if-kyle/goaccess.git
cd goaccess
docker build -t goaccess .
docker run -it --rm --entrypoint=sh goaccess
sh init.sh
```
=> alpine doesn't have bash, so convert to sh

src/settings.c
Probe for user's goaccessrc first, then fallback to system default.
=> Parse user configuration first when available (fixes #693)

Dockerfile, README, README.md
Move from 8080 to 7890.
This should avoid confusion like in #727. Since no `goaccess.conf` is provided by default, use the default port where goaccess lives on.
=> Expose default Goaccess port

src/websocket.c
fixes #448
`get` substring may happen in additional headers (i.e. `Host:` one)
so parsing will fail resulting in 400 return code (Bad request)
=> websocket: use uppercase method name only

configure.ac
With OpenSSL 1.1, many deprecated functions were removed.  Unfortunately,
the current configure script checks for these functions, causing an error
during compiling.
Change the script to look for non-deprecated functions, which exist
on both 1.0 and 1.1.
This fixes the build on Debian and Arch, and closes #591.
Signed-off-by: Sean Cross <sean@xobs.io>
=> autoconf: use non-deprecated functions for lssl, lcrypto test

resources/js/app.js
This solves a problem I was experiencing on Firefox, where I had to manually specify --ws-url=wss://hostname
It is now inferred that the protocol should be wss:// when connecting via https.
=> js: app: use wss:// when connecting via https

src/gwsocket.c, src/websocket.c
These two patches solved a problem I was experiencing when doing:
ssh -i [key] core@remote.local docker logs -f [container] | ./goaccess -o report.html -a --log-format=COMBINED --real-time-html
The root cause is that the primary thread runs before mkfifo() is called.  Running goaccess under valgrind or "strace -ff" was usually enough to get it working, but this patch fixes this race condition.
=> Fix startup websocket race

Dockerfile
mainly for signal handling, i.e. make `docker stop` graceful (and faster).
See also, https://github.com/krallin/tini
or https://github.com/krallin/tini/issues/8
Thanks for the nice tool!
=> [docker] Add tini as minimal init system

src/parser.c
the `~h` option to parse XFF headers conflicted with the `%~` option and
made it non-working
I was trying to parse a Squid logfile in native format (see attached log), which uses a variable number of spaces before the field for processing time. With the current goaccess v1.2 release, the `%~` is not working (with v1.1 neither; more I did not check), because the code enters that path for parsing the XFF header (which obviously fails) upon encountering a `~`. This PR should fix the behavior by checking if a `%` has been encountered before, in which case the 'blank eater' should be executed.
Compilation options:
```
./configure --enable-utf8
make
./goaccess -p goacces.conf -o report.html squid_test.txt
```
output:
```
squid_test.txt [0/s]
Parsed 10 linesproducing the following errors:
Token …
```
=>  fix broken `%~` parse specifier

src/commons.c, src/options.c, src/settings.h
This is useful when piping in logs for processing in which the log size can be explicitly set.
=> Add log-size switch handling: [-S|--log-size]

src/options.c
=> options.c: Fix conf.filenames duplication problem if logs are via pipe.

src/options.c, src/util.c, src/util.h
=> Add valid_output_type() to validate the filename given via '-o'

src/goaccess.c, src/json.c, src/options.c, src/settings.h, src/tcabdb.c, src/tcabdb.h
This was done to facilitate the processing flow of adding daily logs to the stored tcb files
and then running the daily report against it.  This problem was that 'Init. Proc. Time' only
showed the processing time for the current processed log, however we need it to show the
accumulated time over the entire monthly report processing span.
=> Add ability to store accumulated processing time into DB_GEN_STATS tcb file via '--accumulated-time' switch

src/browsers.c
Hi. I've added "Tiny Tiny RSS" to the "Feeds" category in `browsers.c`. [Tiny Tiny RSS](https://tt-rss.org/) is a self-hosted and web-based RSS feed reader with a user-agent string like: `Tiny Tiny RSS/17.4 (http://tt-rss.org/)`. I hope, this is helpful and I can contribute to your project with this pull request.
I compiled this, but in the terminal ui interface, only `Tiny Tiny` instead of `Tiny Tiny RSS` is displayed within the "Browsers" section (see attachment). I don't know if this is a bug or expected behavior. Maybe the string is cut because of spaces between the words?
To test this, I've compiled with `{"TinyTinyRSS", "Feeds"}` (without spaces) and a test log which contains such a user-agent: `TinyTinyRSS/17.4 (http://tt-rss.org/)`. Then `TinyTinyRSS/17.4` is displayed.
=> Added "Tiny Tiny RSS" to browsers.c file.

src/parser.c
https://travis-ci.org/allinurl/goaccess/jobs/305616842#L2488-L2491
```
src/parser.c:2356:7: warning: comparison of array 'hour' equal to a null pointer
is always false [-Wtautological-pointer-compare]
if (hour == '\0')
^~~~    ~~~~
1 warning generated.
```
=> parser.c: fix warning: comparison of array 'hour' equal to a null pointer is always false

src/settings.c
https://travis-ci.org/allinurl/goaccess/jobs/305616842#L2496-L2499
```
src/settings.c:238:22: warning: expression which evaluates to zero treated as a
null pointer constant of type 'char *' [-Wnon-literal-null-conversion]
_argv[*argc + 1] = '\0';
^~~~
1 warning generated.
```
=> settings.c: fix warning: expression which evaluates to zero treated as a null pointer constant of type 'char *'

Dockerfile
Addresses: [Goaccess docker ssl-cert unrecognized #1030](https://github.com/allinurl/goaccess/issues/1030)
I cloned the goaccess repo, changed the docker file as follows:
* apk added [openssl-dev](https://pkgs.alpinelinux.org/package/v3.3/main/x86/openssl-dev) similar to [libssl-dev](https://packages.debian.org/jessie/libssl-dev) (couldn't find libssl-dev for `apk`)
* added `--with-openssl` to the goaccess build configuration (in Dockerfile)
I built and tested the resulting image with valid certificates and a socket connection with `wss://` worked.
@allinurl  let me know what you think. If approved, I'll update the Readme file and docs as well.
=> Add SSL support for docker goaccess build

README.md
Provides an example of configuring a secured connection
with `ssl-cert` and `ssl-key` config properties
in the Docker section of README.md.
(as promised in PR #1036)
=> Update README.md with wss support in Docker

goaccess.1, src/tcabdb.c, src/tcbtdb.c, src/tcbtdb.h
When we start multiple (btree enabled) goaccess processes, each of them gets a uniq folder for its database files. (Only if no db-path is specified, neither in the config file nor with the --db-path CLI argument). This makes parallel processing possible in an easy way. The extra folder is removed at the housekeeping.
=> uniq (default) dbpath for each process

src/commons.c
I added configure arguments to the `--version` output. As suggested in #940 
If anything is wrong or you would like this implemented in different way, I would be happy to change anything. 😃
I thought this had been referenced in another issue also but I can't find it.
=> added configure arguments to --version output

resources/js/app.js, resources/tpls.html, src/labels.h, src/output.c
I added `First` and `Last` buttons to the html report. As suggested in #902 
This isn't ready to merge yet because it looks like you've created a min version of Font Awesome that only has the icons needed for the report. How did you make this? Right now the `First` and `Last` buttons are using the same icons as `Previous` and `Next`. Is there a way to add icons for `<<` and `>>`?
Also the double chevrons to match the chevrons for `Previous` and `Next` are part of the pro Font Awesome. So it might be better to use `fa-angle-left` and `fa-angle-double-left` so they match.
=> added first/last buttons to html report

src/parser.c
Sorry I missed this. After the call to `set_time` the token can be freed.
=> added missing call to free()

src/ui.c
Just fix some small typos I noticed while working on datetime things.
=> fixed typos in function definition comments

Makefile.am
This is a follow up to the comments on 4b8346e
The default `sed` on mac does not support the `*?` non-greedy operator. Which is why `resources/js/charts.js.tmp` and `resources/js/app.js.tmp` were empty and I was getting the error: `RE error: repetition-operator operand invalid` So I removed the non-greedy operator. I don't think it's needed in this context.
I also noticed that the files produced by the default sed on mac were not the same as files produced by GNU sed. I replaced `[ \t]` with `[[:space:]]` and now files produced by default mac sed and GNU sed are identical.
=> Make regular expressions POSIX compatible

src/output.c
Server statistics is assumed to be a private page, so don’t send the HTTP Referer (sic) request header with any external links to keep information about the existence of the page from leaking.
https://www.w3.org/TR/referrer-policy/#referrer-policy-no-referrer
https://www.ctrl.blog/entry/private-bts-referrer-header
=> Unset referrer header

src/options.c
The missing include yielded a warning about the implicitly declared
function which was therefore defined by default to return type 'int'
which on 64-bit systems is not large enough to hold the return type
of a malloc pointer, causing the segfault when the invalid pointer
was dereferenced. Phew!
Fixes https://github.com/allinurl/goaccess/issues/1168
Signed-off-by: Joe Groocock <me@frebib.net>
=> Add missing include for xstrdup. Fixes #1168

src/parser.c
A loop feel like better, if you don't mind it calculate the string length on fly, please remove the below part (will be cleaner), and use `strlen()` instead of `list_length`.
```c
// Length of every string in list
static int list_length[sizeof(list) / sizeof(*list)] = { -1 };
// Only calculate length on first time
if (list_length[0] == -1) {
for (int i=0; i < list_count; i++) {
list_length[i] = strlen(list[i]);
}
}
```
PS. I am not good in C, I have tested but please test again 😊 .
=> Rewrite extract_method

src/browsers.c
The baiduspider's mobile User-Agent is
"Mozilla/5.0 (Linux;u;Android 4.2.2;zh-cn;) AppleWebKit/534.46 (KHTML,like Gecko) Version/5.1 Mobile Safari/10600.6.3 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)",
but it is not a Safari browser.
=> Change browser compare order

src/browsers.c
Hi, I have some crawlers found in my log-files. I don't know what PxBroker really is, but Seekport is an old search engine (currently disabled) but their bots seems to be active...
Greetings,
Alex
=> Added some crawlers

src/tcabdb.c
Thanks for the great software.
I noticed that when using Tokyo Cabinet btree storage the VISITORS section of HTML report randomly changed dates. This patch fixes the issue.
The issue is shown in this youtube video: https://youtu.be/yp8jgVLTWs8
=> Fix parse_raw_data for VISITORS module when using Tokyo Cabinet

src/settings.c
#694 results in ~/.goaccessrc always being used, the fallback to the global config file is broken. It appears that the code is assuming that realpath() will return NULL if the file does not exist, which is not the case. Unbreak by actually attempting to open ~/.goaccessrc and falling back to global config if this fails.
=> Fix fallback to global config

config/goaccess.conf, goaccess.1, src/options.c, src/parser.c, src/settings.h
To avoid logging IP addresses, users may obfuscate them using a
regularly rotated seed and an hash algorithm. For nginx, [ipscrub][]
can be used for such a task. However, the result is not a valid IP
address.
This commit adds an option, `--no-ip-validation`, to avoid checking
the validity of an IP address and use the provided field as is. The IP
is stored as a string and the current code correctly handles the case
where this field is not an IP address (`inet_pton()` is checked with
`AF_INET`, then `AF_INET6` and falls back to some sensible behaviour
for other cases).
Fix #1354
[ipscrub]: https://github.com/masonicboom/ipscrub
=> Add an option to disable client IP validation

Makefile.am
autoconf/automake usually allows a user to do an out-of-tree build:
mkdir build
cd build
../configure
make
This is convenient to easily start from scratch by just removing the
`build` directory (whatever we are working from a git checkout or a
tarball).
To make it work, manually written rules, like these used to embed
HTML/JS/CSS resources, need to be rewritten to correctly address
source files.
=> Enable out-of-tree builds

src/util.c
Since v1.3, goaccess will install default config to `/etc/goaccess/goaccess.conf`:
https://github.com/allinurl/goaccess/blob/b43934e4a383070de936f513a06e45f424691223/Makefile.am#L119
But when goaccess is run after installation, it will look at old location, `/etc/goaccess.conf` instead.
This change fixes default config file lookup to match installed location.
Without the change, on a fresh install:
goaccess --dcf
No default config file found.
You may specify one with `-p /path/goaccess.conf`
strace reveals: 
lstat("/etc/goaccess.conf", 0x7ffe8846a0e0) = -1 ENOENT (No such file or directory)
After the change, on a fresh install:
goaccess --dcf
/etc/goaccess/goaccess.conf
=> Fix path to default config

ChangeLog
This feature has been released as hide-referer and is already documented in another line.
=> Fixes #1419: ignore-referer-report wasn't released under that name

src/output.c
If html file didn't have a icon link,browser may request a facicon.ico
from the root uri which may not have on the server, and it will return
a 404 error code.
this might not work for browsers lower than IE8
Fix #1432
I am not familiar with c ,this is the best i can do :)
=> Add base64 encoded favicon to html output

src/browsers.c
Removed Flock (not maintained for the last eight years.)
=> Add Beaker, Brave, and Firefox Focus

src/ui.c, src/ui.h
Closes https://github.com/allinurl/goaccess/issues/1362
Tested with ~10MB access.log file, and observed a newline added correctly:
```
$ goaccess access.log -o report.html --log-format COMBINED
Parsing...[58,556] [58,556/s]
$
```
=> Close #1362 - fix newline when print to stdout/stderr

Dockerfile
- `libressl` no longer uses source code compilation to speed up the docker image build.
- add ` --enable-geoip=mmdb` flag to support GeoIP
=> GeoIP for docker image

config/goaccess.conf
I understand that `crawlers-only` is the opposite part to `ignore-crawlers`, so the comment can't be `This will ignore robots listed under browsers.c`?
=> Typo in goaccess.conf

README.md
This was a showstopper for me, when I tried the docker variant to analyse a Tomcats access log.
=> Add info about predefined log-format options

README.md
Fixes https://github.com/allinurl/goaccess/issues/1520
=> Typo: Docker commandline example doesn't work

config/browsers.list, src/browsers.c
Add crawlers that are routinely showing up as real hits to the crawlers list.
=> Add DuckDuckGo and MSNBot browsers to the crawlers list.

README.md
Issue #1494 
I didn't edit the part regarding `cert.key`
```
or for secured connections (TLS/SSL), please ensure your configuration file
contains the following lines:
ssl-cert /srv/data/domain.crt
ssl-key /srv/data/domain.key
ws-url wss://example.com:8080
```
I'm not sure about those paths.
=> updating docker container default paths for logs,report,data

config/podcast.list
This is a list of podcast related agent strings.
It may be useful for people who host their podcast media files on their own servers.
=> added list with podcast-related agent strings

src/commons.h, src/csv.c
This patch fixes build error like this:
```
make[2]: Leaving directory '/builddir/build/BUILD/goaccess-1.3'
/usr/bin/ld: src/color.o:/builddir/build/BUILD/goaccess-1.3/src/commons.h:47: multiple definition of `now_tm'; src/browsers.o:/builddir/build/BUILD/goaccess-1.3/src/commons.h:47: first defined here
/usr/bin/ld: src/commons.o:/builddir/build/BUILD/goaccess-1.3/src/commons.h:47: multiple definition of `now_tm'; src/browsers.o:/builddir/build/BUILD/goaccess-1.3/src/commons.h:47: first defined here
/usr/bin/ld: src/csv.o:/builddir/build/BUILD/goaccess-1.3/src/commons.h:47: multiple definition of `now_tm'; src/browsers.o:/builddir/build/BUILD/goaccess-1.3/src/commons.h:47: first defined here
/usr/bin/ld: src/error.o:/builddir/build/BUILD/goaccess-1.3/src/commons.h:47: multiple definition …
```
=> Fix build with GCC 10

src/gkhash.c, src/tpl.c, src/tpl.h
- Enable check for variable arguments
- Add attribute to struct member
- Use %zu instead of %d specifier for size_t arguments
```
src/tpl.c:1120:71: warning: format specifies type 'int' but the argument has type 'size_t' (aka 'unsigned long') [-Wformat]
tpl_hook.oops ("tpl_dump: buffer too small, need %d bytes\n", sz);
~~           ^~
%zu
src/tpl.c:2447:51: warning: format specifies type 'int' but the argument has type 'size_t' (aka 'unsigned long') [-Wformat]
tpl_hook.oops ("tpl exceeds max length %d\n", tpl_hook.gather_max);
~~     ^~~~~~~~~~~~~~~~~~~
%zu
src/tpl.c:2522:57: warning: format specifies type 'int' but the argument has type 'size_t' (aka 'unsigned long') [-Wformat]
tpl_hook.oops ("tpl exceeds max length %d\n", tpl_hook.gather_max);
~~     ^~~~~~~~~~~~~~~~~~~
%zu …
```
=> Improve function format attribute

config/goaccess.conf
.dmg is the most commonly used extention for Apple Disk Image files,
.xz is used by XZ Utils, and .zst is used by Zstandard.
=> Add .dmg, .xz, and .zst to the static list.

src/goaccess.c
Allows longer translations for help and closing texts.
See https://github.com/allinurl/goaccess/pull/1802
=> Extend text space in footer

README.md
The `zypper ar` line resulted in an error as a repo name is required.
Given the `-f` (autorefresh) option is specified, manually refreshing (`zypper ref`) is not really needed.
=> README: update openSUSE instructions

README.md
This way is simpler.
I took it in https://github.com/allinurl/goaccess/issues/1693#issuecomment-594819061
=> README.md: Use zcat instead of pipes

Dockerfile
Removed license statement in the `Dockerfile` to conform to the primary license.
=> Remove license statement in Dockerfile

Dockerfile
Fix problem with Docker image build failure because `libmaxminddb` was not found.
=> Fix missing libmaxminddb

src/json.c
There is a small typo in src/json.c.
Should read `output` rather than `ouput`.
=> docs: fix simple typo, ouput -> output

configure.ac
We need to link to libintl to get dgettext.
We need to link to curses to get refresh.
test == is not portable, test = is.
Signed-off-by: Roy Marples <roy@marples.name>
=> configure: Work on NetBSD

src/goaccess.c, src/options.c, src/options.h, src/ui.c, src/ui.h
usleep(2) also has no effect if equal to greater than 1000000
which happens to match HTML_REFERS, but no error was checked.
This caused 100% CPU utiliation constantly following the tail
of the web server access log with default value.
nanosleep(2) has more relaxed limits.
This commit does a like for like replacement and also adds
error checking in case of a similar error in the future.
Signed-off-by: Roy Marples <roy@marples.name>
=> POSIX has made usleep(2) obsolete in favour of nanosleep(2)

configure.ac, src/gdashboard.c, src/websocket.c
While here, respect the host default compiler of cc.
If that fails, then try gcc and finally clang.
Now I can do
./configure
make
and there are zero warnings when cc is clang on NetBSD.
=> Fix build when clang is the compiler

Makefile.am, configure.ac
This allows goaccess to be built with address sanitisation on NetBSD, otherwise it would not know which SHA1 functions to use.
=> Detect SHA1Init in libc and use that instead of our own sources

src/browsers.c
This massively reduces the "unknown" entries in the browser section of my reports.
* Waterfox & PaleMoon are Firefox forks, so I assigned them to "Firefox"
* Pleroma is used by the decentralized, mastodon compatible Pleroma (when fetching "link previews" for the timeline I guess), Brainstorm seems to be a bot fetching content for Reddit, Mastodon & Matrix – hence I assigned both to "Feeds"
* F-Droid is used by the official [F-Droid](https://f-droid.org/) Android client, okhttp by several Android apps – hence assigned to "Others"
"F-Droid" will probably only show up on servers providing F-Droid app repositories. I'm running such a repo, hence I'm interested in having it defined – but if that's not wanted "globally" I fully understand and would "patch" it on my end before compile, just let …
=> add some browsers

src/browsers.c
Some more UAs:
* Aptly: used by Ubuntu (in context of APT actions)
* Mastodon: like Pleroma from my last PR
* PrivacyBrowser: an Android web browser
=> add Aptly, PrivacyBrowser, Mastodon UA

src/geoip1.c
This implements and thus closes #2020
=> Handle case when IPv4 is encoded as IPv6 in GeoIP1

src/opesys.c
=> Don't call unknown Linux systems "GNU+Linux"

src/opesys.c
Solaris/SunOS/illumos is an actual UNIX, not just "Unix-like"; also, added AIX (which is still alive).
=> Add a new category for Unix

resources/js/app.js
GoAccess defaults to the darkPurple theme even for us weirdos :-) who still prefer the Light Mode in 2021. This change defaults to "bright" for us and "darkPurple" for them.
=> Dark Mode detection

config/goaccess.conf
Now that GoAccess prefers "referrer" over "referer", the example configuration file should probably cover that.
=> Rename referer to referrer in goaccess.conf

src/gholder.c
See [issue 2106](https://github.com/allinurl/goaccess/issues/2106).
=> Check item.hits in map_data to protect against divide by zero

Makefile.am
Out-of-tree build was fixed in 51632aaedafc, but for some reason, I
have missed an occurrence.
=> Fix out-of-tree builds

src/parser.c
Check if requested string is long enough for comparison.
==65303==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000013a4d at pc 0x00000043e1cb bp 0x7ffe4e3c09a0 sp 0x7ffe4e3c0140
READ of size 1 at 0x602000013a4d thread T0
#0 0x43e1ca in __interceptor_strncasecmp (/home/christian/Coding/workspaces/goaccess/goaccess+0x43e1ca)
#1 0x5922e0 in verify_static_content /home/christian/Coding/workspaces/goaccess/src/parser.c
#2 0x5922e0 in is_static /home/christian/Coding/workspaces/goaccess/src/parser.c:1487:10
#3 0x58ecbc in pre_process_log /home/christian/Coding/workspaces/goaccess/src/parser.c:1775:12
#4 0x593bd5 in read_line /home/christian/Coding/workspaces/goaccess/src/parser.c:1797:14
#5 0x593bd5 in read_lines /home/christian/Coding/workspaces/goaccess/src/parser.c:1914:16 …
=> Avoid buffer underflow

src/parser.c
This PR will fix a tiny 'problem' with checking pointer-validity "too late", i.e. after it is already dereferenced.
See https://github.com/allinurl/goaccess/blob/master/src/parser.c#L435
Problem:  pointer 'req' is dereferenced (at line 437 by `strlen(req)`) before being checked against NULL (at line 441)
Solution: move check up before use, e.g. move if-stmt at line 441 to line 437 so that this code
```C
435  static int
436  verify_static_content (const char *req) {
437    const char *nul = req + strlen (req); // <-- dereferences pointer 'req'
438    const char *ext = NULL, *pch = NULL;
439    int elen = 0, i;
440  
441    if ((req == NULL) || (*req == '\0'))  // <-- check validity of pointer 'req' (after it was dereferenced)
442      return 0;
```
... becomes
```C
435  static int
436 …
```
=> Fix minor time-of-use / time-of-check "bug" in src/parser.c

README.md
Realtime requires the usage of tail instead of cat. Otherwise there are no updates
=> Docker realtime requires tail instead of cat

src/settings.c
Check before calling xstrdup, which does not accept a NULL pointer,
whether argv[0] is actually set.
=> Do not crash on argument counter of zero

config/goaccess.conf, src/settings.c
This should adddress CADDY's v2.5.0 change where the remote port has its own
JSON property.
Fixes #2220
=> Removed the remote port portion from the host format.

src/geoip2.c
Currently, goaccess will only display host cities if the geoip database type id matches Maxmind's. This relaxes the check to match the DBIP City Lite database as well.
=> Show city with the DBIP City Lite database too.

goaccess.1, resources/js/app.js, src/options.c, src/output.c, src/settings.h
Solves #1663
Some notes:
- there is no way to send "real" ping/pong frames (sections 5.5.2 and 5.5.3 of [RFC 6455](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.2)) with the JavaScript WebSocket API - further discussion [here](https://stackoverflow.com/questions/10585355/sending-websocket-ping-pong-frame-from-browser)
- the implemented ping mechanism consists in sending plain text from the client-side JavaScript WebSocket; this is because [gwsocket.io](https://gwsocket.io/) (server-side) already supports standardized ping/pong frames as shown below:
https://github.com/allinurl/goaccess/blob/b30282947bacff987407a71aeb4c5f7a47e6cdf3/src/websocket.h#L151-L152
https://github.com/allinurl/goaccess/blob/b30282947bacff987407a71aeb4c5f7a47e6cdf3/src/websocket.c#L1912-L1919
so I …
=> Add option --ping-interval=<secs>

Dockerfile
Alpine 3.13 will no longer regularly receive security fixes after November 1st.
=> Update Dockerfile build stage to use alpine:3

config/goaccess.conf, goaccess.1, src/browsers.c, src/options.c, src/settings.h
As an attempt to detect non-humans more accurately, an option to
classify unknown OS and browsers and crawlers help. In my case, I have
20% visitors with unknown OS and 12% with unknown browser. Here is the
top list from last month:
```
509 python-requests/2.25.1
534 googlebot
563 Mozilla/5.0 (compatible; CensysInspect/1.1;  https://about.censys.io/)
567 WordPress/5.1.5; https://takefive.cn
573 http.rb/4.4.1
612 MB-Web-Crawler
624 GoodBot
624 lanaibot please contact contactlanaibot@gmail.com for information
709 Mozilla/5.0 (compatible; SEOkicks;  https://www.seokicks.de/robot.html)
762 https://github.com/blakeembrey/popsicle
768 Mozilla/5.0 (compatible; Neevabot/1.0;  https://neeva.com/neevabot)
891 MauiBot (crawler.feedback wc@gmail.com)
933 Buck/2.2; ( …
```
=> Add an option to classify unknown OS and browsers as crawlers

.github/workflows/docker-publish.yml
Today docker hub registry contains only amd64 architecture.
This PR modifies docker publish script in order to have multiple architectures available. In this case arm64 and amd64.
The image is published only when there is a tag on the master branch.
4 labels are published:
* latest
* version (ex. 1.7.1)
* major.version (ex. 1.7)
* major (ex. 1)
I have tested this in my fork [hub.docker.com/r/cristianpb/goaccess/tags](https://hub.docker.com/r/cristianpb/goaccess/tags)
=> 🐳 Build docker image on different architectures

inlang.config.js, po/de.po, po/es.po, po/fr.po, po/goaccess.pot, po/it.po, po/ja.po, po/ko.po, po/pt_BR.po, po/ru.po, po/sv.po, po/uk.po, po/zh_CN.po
Hi,
Changes
- added an inlang.config.js file to the root of the repo
- updated and fix German translations
I saw your german translation was broken. To make it easier for me to contribute to your translation, I added the tool [inlang/inlang](https://github.com/inlang/inlang). I am opening this PR as a draft to discuss the tool. Maintainers or contributors would have no overhead as inlang is built on git. No accounts (login with GitHub), no sync, and no pipelines are required. Contributions open a PR.
Would an UI over the translations in this repo be of benefit to the goaccess community?
You can try it out on my fork and post your feedback under this draft.
https://inlang.com/editor/github.com/jannesblobel/goaccess
The PR is theoretically ready for review.
=> Update german Translation and init inlang

src/parser.c
On FreeBSD, goaccess dumps core when reading from STDIN.
FreeBSD's basename(3) behaves a little different from the rest of the world. Rather than sometimes returning a pointer to a new allocation, it always returns a pointer into the buffer itself.
When basename() gets a string, including an empty string, it behaves as expected. But if it's given a null pointer, it returns another null pointer rather than a pointer to a newly-allocated empty string. This makes it thread-safe, but (as usual for FreeBSD) assumes that the rest of the world enjoys FreeBSD's quirky null pointer exceptions.
When reading from STDIN, the filenames vector is empty, so set_glog's filename arg is empty. Calling basename on it makes a null pointer, and subsequent use causes a segfault.
Calling xstrdup on the filename …
=> Fix null pointer exception on FreeBSD (fixes #2476)

ChangeLog, build-dynamic.sh, config/goaccess.conf, goaccess.1, src/geoip2.c, src/labels.h, src/parser.c, src/tpl.c
Only comments and display strings are changed here.
Notable here is the correction of referer => referrer. "Referrer" is the actual spelling; "referer" was a misspelling that made it into RFC 1945 (see 1).
It makes the most sense to use "referer" when referring to the HTTP header, and "referrer" when referring to an actual referring page.
[1]: https://en.wikipedia.org/wiki/HTTP_referer
=> Fix spelling errors as reported by the spellcheck action

README.md
Hey there, we want you to get more contributors to your repository!
Therefore, I added a badge which lets users contribute to your translations.
The badge endpoint allows you to create a dynamic badge that display real-time data on your project. For instance, you can use it to showcase your project's localization progress or the number of errors/warnings on your Github repository. This means that whenever someone views the badge, they will see the most up-to-date information about your project.
For your project, the badge looks like this:
(this image is already auto generated)
[![translation badge](https://inlang.com/badge?url=github.com/allinurl/goaccess)](https://inlang.com/editor/github.com/allinurl/goaccess?ref=badge)
We would be really happy if you decide to place this into your …
=> add translation status badge to README

src/opesys.c
Referring to macOS (previously OS X, before that Mac OS X) as "Macintosh" is archaic terminology. Fixed that.
=> Macintosh -> macOS

src/gstorage.c
This pull request addresses Issue #2580, where the GoAccess log parser fails to recognize the 'SEARCH' HTTP method.
=> Add SEARCH method in gstorage.c

src/gstorage.c
I found this heap-buffer-overflow issue when debugging with ASAN (`-fsanitize=address`). And here is the proposed solution.
```c
char browser_type[BROWSER_TYPE_LEN] = "";
logitem->browser = verify_browser (ua, browser_type);
logitem->browser_type = xstrdup (browser_type);
if (!memcmp (logitem->browser_type, "Crawlers", 8)) {
// ...
}
```
```
127.0.0.0 - - [10/Dec/2023:19:30:00 +0800] "GET / HTTP/1.1" 200 1234 "-" "Edge/42"
```
Since the User-Agent resolved to `browser_type="Edge"`, it only have 4+1 bytes length. When `memcmp()` for 8 bytes, it will touch the improper memory.
I think using `strncmp` instead of `memcmp` is the most intuitive way to avoid this problem.
The string length should be 8 char + null = 9 bytes.
```c
if (!strncmp (logitem->browser_type, "Crawlers", 9)) {
// ...
} …
```
=> Fix heap overflow in set_browser_os()

src/goaccess.c
nginx uses `SIGQUIT` as the signal for a graceful shutdown (https://docs.nginx.com/nginx/admin-guide/basic-functionality/runtime-control/)
some context:
- https://github.com/nginxinc/docker-nginx/issues/377
- https://github.com/nginxinc/docker-nginx/issues/167
- https://trac.nginx.org/nginx/ticket/753
In their Dockerfile they also use 
[`STOPSIGNAL SIGQUIT`](https://github.com/nginxinc/docker-nginx/blob/4bf0763f4977fff7e9648add59e0540088f3ca9f/mainline/debian/Dockerfile#L117)
when also running `goaccess` in the same container via [`dumb-init`](https://github.com/Yelp/dumb-init) or something similar, goaccess will exit non zero upon receiving `SIGQUIT` hence the container shutdown will also have a non zero exit code and tools like docker-compose or an `ansible`-based deployment will treat …
=> handle SIGQUIT as a signal for a graceful shutdown

ChangeLog, README.md, config/goaccess.conf, goaccess.1, src/settings.c, src/settings.h, src/ui.c
hey @allinurl ,
I've seen you are still very active in your repository. I've seen you have regular requests for traefik (e.g. #2368 , #1660 and #966) log format.
Here is my take at a default setting that worked for me and is according to the documentation https://doc.traefik.io/traefik/observability/access-logs/ .
Please not that I have no knowledge of GO. I just copied and adapted the existing code. So feel free to close this PR if it is not useful.
Also I don't know if you have unit tests where I could add some dummy logs for testing?
Greetings and thanks for the great tool.
=> feat(settings): add traefik log format

README.md, goaccess.1, src/options.c
just some small changes to the documentation:
- mount the report file in the docker documentation (so juniors will have a few less google searches on how to access the result)
- add a note about the contradiction between `-a` and `--anonymize-ip`
again please not that I have no knowledge of the documentation engine you are using so feel free to hint me to other locations where this needs adaption.
=> doc: add minor documentation

src/opesys.c
When processing requests from Android version 12.1, the report was generated as Eclair 2
=> fix: add android 12.1 in operating systems

src/parser.c
This fixes a bug, where the referer parser chokes on some rare URLs where the URLs parameter appear without a `'/'` character marking the end of the host, e.g. the following URL:
```
https://example.com?ref=https%3A//giter.vip
```
Before this fix, goaccess would mistakenly display `"https://example.com?ref=https%3A"` as the referer host.
Example nginx log file:
```
1.2.3.4 - - [07/Jul/2023:19:12:21 +0200] "GET /example/ HTTP/1.1" 200 5910 "https://example.com?ref=https%3A//giter.vip" "Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot)"
```
While it is more common to have a `'/'` before the URL parameters, the above is perfectly valid according to the spec, see here: …
=> Extract referer host more reliably

po/de.po
Corrected a few minor spelling, grammar and other mistakes. A couple of notes for other translators:
- In German, the short dash `-` (Bindestrich) is used for composite nouns (multiple dashes for multiple nouns within a single composite word), whereas the longer one `–` (Gedankenstrich) is used for interjections in sentences.
- After the Gedankenstrich `–`, the next character is always in lower-case (except if the word is a noun, obviously).
- Verbs used as nouns are capitalised.
Replaced the English term “panels” with “Kacheln” which means “tiles”, for stylistic reasons; hope that's okay.
=> Minor fixes in German locale

src/opesys.c
Apple renamed "OS X" to "macOS" 8 years ago, so newer tools do not report "OS X"  anymore.
=> Add support for macOS to the OS detection

config/goaccess.conf, src/settings.c
Caddy has added [first-class support for determining client IP](https://github.com/caddyserver/caddy/pull/5104), which means that from Caddy 2.7 beta 1 onwards, the logs include `client_ip` alongside `remote_ip` in the access logs. The value falls back to `remote_ip`'s value, meaning this has no impact on Caddy configurations that don't use trusted proxies.
> the client_ip should always be set (as long as the RemoteAddr is a valid IP address). So in the logs, it will be identical to the remote_ip unless trusted proxies is configured and the proxy passed the client IP in a trusted header.
If trusted proxies are [configured globally](https://caddyserver.com/docs/caddyfile/options#trusted-proxies), Caddy will follow your configuration for determining which proxies are trusted and what …
=> Use `client_ip` for Caddy JSON, allowing trusted proxies

README.md
As of (at least) Ubuntu 22.04 LTS and Debian Buster, there is no longer a `w6-dev` package. The build works as expected with `libncurses-dev` instead.
This is a quick fix only based on the latest releases to keep the readme simple. Please reject this patch if you intend to maintain docs for older Ubuntu/Debian versions.
I tested in a `ubuntu:22.04` container. I installed these packages prior to building:
* autoconf
* automake
* autopoint
* gcc
* gettext
* libncurses-dev
* libgeoip-dev
* libmaxminddb-dev
* libssl-dev
* build-essential
=> update ncurses dependency for Ubuntu/Debian

src/browsers.c, src/color.c, src/commons.c, src/commons.h, src/csv.c, src/gholder.c, src/gkhash.c, src/gkhash.h, src/gkmhash.c, src/gkmhash.h, src/gstorage.c, src/gstorage.h, src/json.c, src/opesys.c, src/options.c, src/output.c, src/parser.c, src/persistence.c, src/settings.c, src/sort.c, src/ui.c, src/ui.h, src/util.c, src/websocket.c
* Constify read-only data
Declare read-only data arrays const, to warn on accidental modification and let compilers place them in read-only memory sections.
* De-duplicate strtoupper()
Avoid the duplicate definition of strtoupper() in websocket.c, just use the one from util.h.
* Avoid UB in character checking functions
The functions classifying characters like isspace(3) require the input to be of type unsigned char or EOF.
* Avoid out-of-bounds access in serial processing mode
When using just one job for processing the input lines do not use the out-of-bounds index 1 instead of the valid one 0.
This currently seems to only work since the stack space of the in this case unused threads array is used.
* Insert the status code in the correct position
* Avoid out-of-bounds access for invalid …
=> Miscellaneous bug fixes and improvements

config/browsers.list
fixes `Duplicate browser entry: DotBot` error when this file is used with `browsers-file`
=> remove dup DotBot in browsers.list

src/parser.c
We use this, but it may not be included via other headers; fixes building on AIX.
=> Include stdint.h

src/websocket.h
We're already on the network byte order, there's no need to swap bytes. For instance, AIX doesn't have a header for this, but it's already on a big endian platform, so it's unnecessary.
=> Don't swap bytes on big endian platforms as a fallback

src/gstorage.c
When I specified the flag `--4xx-to-unique-count` I expected to see non-zero visitors for 4xx requests in dashboard, but nothing changed.
Fixed bug with incorrectly checked 4xx status codes when `--4xx-to-unique-count` flag is specified.
The bug was introduced in commit 6d2cb7e.
=> Fix bug related to `--4xx-to-unique-count` flag logic.

src/labels.h, src/parser.c
Closes #2818
In https://github.com/allinurl/goaccess/issues/2818#issuecomment-2778983916 I was proposing also to change top line with the count as well (since there could be more than 10), but with all the i18n, decided not to overdo for this
=> Provide a hint about --invalid-requests whenever parser fails

src/parser.c
Changed src/parser.c so that error messages are more understandable.
I have spend way too long trying to figure out what "IPv4/6 is required" is.
I think it'd be more user friendly to have additional message for a user to tell him what exactly he needs to do.
If I only have that message I think I'd be done with my task way sooner.
P.S.
I like this project once I got it working . I also have a things I wanna change. I look forward to it.
I have also seen a lot of issues in this repository that mention this error and people are stuck, so I think this will also help them, help you because you will no loger get the same issues opend ( hopefully. ( most likely no lol ) )
=> Make error messages more actionable.

config/goaccess.conf
I got confused when i enabled the GEO_LOCATION panel to discover an "ASN Panel" that wasn't mentioned anywhere in the goaccess.conf parameters list.
This pull request updates the `config/goaccess.conf` file to include the ASN (Autonomous System Number) panel in both enabled and ignored panel configurations.
Changes to `config/goaccess.conf`:
* Added `#enable-panel ASN` to the list of enabled panels.
* Added `#ignore-panel ASN` to the list of ignored panels.
=> ASN panel mention in goaccess.conf

src/browsers.c
Other bots by OpenAI can be recognised by the heuristic match, so no need to add them.
Closes #2856
=> Add OAI-SearchBot to Cralwers list

src/websocket.c
This PR fixes a potential `NULL` pointer dereference in the `ws_start()` function of the WebSocket server.
If the condition `ncfdstate != nfdstate` evaluates to false during the first loop iteration, the `cfdstate` buffer remains unallocated (`NULL`), but is still passed to `memcpy()`, leading to undefined behavior or a crash.
- `cfdstate` should always be allocated before being passed to `memcpy()`.
- The logic should skip memory operations entirely if `nfdstate == 0`.
- On the first iteration:
- `cfdstate` is initialized as `NULL`.
- If `ncfdstate == nfdstate`, allocation is skipped.
- `memcpy()` is called with a `NULL` destination.
1. Run `ws_start()` when no connections exist (i.e., `nfdstate == 0`).
2. Enter the first iteration of the main loop.
3. Observe a crash or undefined …
=> Fix Potential NULL dereference in ws_start when cfdstate remains uninitialized
