allinurl/goaccess

- src/opesys.c
Add OS X El Capitan in src/opesys.c
> Add OS X El Capitan in src/opesys.c

- README.md
Where is the website's source? It need modification also.
> Added Debian path of sources file

- .gitignore
- Vagrantfile
Set up an environment to build goaccess from github
> Adding Vagrantfile

- src/sha1.c
- src/sha1.h
- src/websocket.h
This PR allows building on illumos-based operating system.
> Fix compilation on OpenIndiana

- goaccess.1
> Unhide Monkai color scheme

- resources/js/app.js
Hi, I think number start with the zero is the programmer's habit not the customer's.
Signed-off-by: Bo Cai <charpty@gmail.com>
> Change grid row number start with 1

- README.md
I pushed a package into OpenIndiana repositories and it should appear in repos in few hours. This PR adds a note how to install goaccess on OpenIndiana.
> Add note about OpenIndiana to README

- Dockerfile
- Dockerfile_src/init.sh
- Dockerfile_src/supervisord.conf
- README.md
I like this project and I was surprised that it doesn't come with Docker support.
Therefore I made a Dockerfile for you, which can be used on Docker Hub to Automatically Build it every time you commit or you release a new version.
At the moment it depends on Alpine package manager to fetch the latest version available, but would be nice to enhance the Docker by fetching the binary from the Releases tab here in Github.
Anyway, feel free to edit parts where you feel comfortable. Build is already tested ( as you can see here https://hub.docker.com/r/julianxhokaxhiu/goaccess/builds/ ).
Fixes #520
> Docker support

- Dockerfile
No reasons to hold us back.
We win also 1MB of free space :)
> Use the latest Alpine image

- src/browsers.c
These are the feed reader services witt the most hits on my site not recongized by GoAccess.
> Add more feed readers

- po/fr.po
Corrects a French spelling mistake.
Sorry for that, I missed it.
> Update fr.po (Corrects a French spelling mistake)

- po/fr.po
I had to review some fields that took up too much space in interface.
I would try next time to do this in one go ;-)
Thanks again for your additions!
> Update fr.po (Small changes and corrections)

- src/options.c
- src/settings.h
- src/ui.c
Reference github: allinurl/goaccess#903
> Add '--no-parsing-spinner' switch

- src/output.c
> output.c: Suppress Google Chrome translation

- src/opesys.c
The Android 8.0 'Oreo' update has been out for a while now.
Even Android 8.1 has released its final developer preview, and will release to the public in December.
> Added 'Android 8 Oreo' to the list of OSs.

- .travis.yml
- YAML indents
- Using build matrix
> Proper Travis usage

- README.md
> Update README.md: Real-time virtual hosts w/ awk

- config/goaccess.conf
- src/commons.h
- src/options.c
- src/parser.c
- src/settings.h
* Added IGNORE_LEVEL_PANEL and IGNORE_LEVEL_REQ definitions
* Allow request to be not counted as valid without ignoring it.
> Allow static file request to be not counted as valid without ignoring it

- README.md
- goaccess.1
I changed ```http://``` links to ```https://``` links in the README and in the Man Page. I made sure to test all the links I changed.
As per the request in this issue: https://github.com/allinurl/goaccess/issues/1039
> changed links from http:// to https://

- src/parser.c
I've been looking at #1056 and #496
As long as the date and time can be parsed as the same field in the log line it seems that these could both be implemented with the `%x` specifier. `strptime` and `strftime` will handle the timezone conversions if you specify the timezone offset with `%z`. The output times will be converted to the local timezone defined by the `TZ` environment variable.
Example Log Lines:
```
1.1.1.1 - - [29/Apr/2018:22:00:00 -0200] "GET / HTTP/1.1" 200 185
1.1.1.1 - - [30/Apr/2018:00:00:00 +0000] "GET / HTTP/1.1" 200 185
1.1.1.1 - - [30/Apr/2018:02:00:00 +0200] "GET / HTTP/1.1" 200 185
```
Formats:
```
log-format %h %^[%x] "%r" %s %b
time-format %d/%b/%Y:%H:%M:%S %z
date-format %Y%m%d
```
When I run this log with these formats I get three hits all for the same time. …
> Parsing Time Zones

- resources/css/app.css
if you click to expand left panel, it takes too long to animation completes
> Speed up animations

- src/opesys.c
Adds Android Pie 9 to get_real_android
> add Android Pie 9 to get_real_android

- src/browsers.c
Hi!
I would like to add some crawlers as well. The named crawlers are mostly active in germany.
Regards,
Christian
> Added somme crawlers

- po/ja.po
> Fix: Japanese lang file

- po/ja.po
`Bandwidth` :arrow_right: `Tx. Amount`. Patched.
> Hotfixes: Japanese lang file

- goaccess.1
> Trivial fixes to avoid manpage warnings

- snap/snapcraft.yaml
Managed to build the snap on *classic* mode relying on *legacy* geoip.
> Basic snapcraft.yaml proposal for iteration.

- po/LINGUAS
- po/sv.po
> Add Swedish

- Dockerfile
- README.md
:warning: **This request makes destructive changes. Please verify and merge.**
Links: #1404
> rewrite Dockerfile

- src/goaccess.c
References #1363 
Handles Ctrl-C (SIGINT) for the curses interface, stopping the program.
Testing:
1). Did Ctrl-C in non-curses interface. Observed the program stop:
```
$ goaccess access.log -o report.html --log-format COMBINED --real-time-html
```
2). Did Ctrl-C in curses interface. Observed the program stop:
```
$ goaccess access.log
```
> Close #1363 - stop program on ctrl-c (SIGINT)

- config/goaccess.conf
typo fifo-out instead of fifo-in
> Typo config file

- Dockerfile
- README.md
- Get time-zone setting from environment variable
- Also modified `README.md`
- Remove unused packages and sorted
> Fix time-zone is not reflected

- README.md
It'd be great if some common mistakes could be caught and referenced, perhaps that can reduce some of the many repeating questions on the issue tracker.
> Added a troubleshooting section to README

- .gitignore
- .travis.yml
- Makefile.am
- configure.ac
- src/bin2c.c
- src/gholder.c
- src/json.c
- src/output.c
- src/parser.c
- src/settings.c
- src/sha1.c
- src/sort.c
- src/tcbtdb.c
- src/util.c
- src/websocket.c
* improve configure script
* fix some compiler warnings
* silence ubsan findings
see single commits for more information
> misc improvements

- config/podcast.list
Minor update of the list, some new podcast-related agents.
> List of podcast related agents updated

- Dockerfile
Add git (required by autoreconf)
> Fix small glitch

- README.md
Resubmitting this as the previous PR was broken.
Resolves #1547
> Add missing gettext build requirement

- goaccess.1
- src/goaccess.c
- src/options.c
- src/settings.h
This makes it trivial to integrate into any OS's init system.
GoAccess should not run as root when producing real time reporting.
> Add option user-name=username

- src/error.c
- src/error.h
- src/gwsocket.c
- src/json.c
- src/json.h
- src/options.h
- src/websocket.c
Adjust non-conforming format strings
> Add format and noreturn function attributes

- po/LINGUAS
- po/ru.po
- po/uk.po
Added Russian and Ukrainian translation files.
> Translation to Russian and Ukrainian

- po/fr.po
We updated the content for french translation. Could you include it in upstream ? Thanks
> Update French translation.

- TODO
- src/commons.c
- src/commons.h
- src/options.c
- src/ui.c
> Use https for the website url

- config/browsers.list
- src/browsers.c
> add discordbot as a bot

- config/browsers.list
- src/browsers.c
> Add YandexBot and Nimbostratus-Bot as crawlers

- src/browsers.c
```
Mozilla/5.0 (compatible; inoreader.com; 1 subscribers)
Mozilla/5.0 (compatible; theoldreader.com)
Mozilla/5.0 (compatible; theoldreader.com; 1 subscribers; feed-id=*some-unique-hash*)
BTWebClient/355S(45724)
```
> A few feed readers

- .github/workflows/docker-publish.yml
> Add github actions

- README.md
Typo which I noticed in the readme. "lastest" should be written "latest"
> Update README.md typo "lastest" to "latest"

- src/browsers.c
Does what #1905 did, but in one commit.
> Add a Bunch of Useragents

- README.md
> Fix typo in zcat argument

- Dockerfile
> Revert "Change base image to scratch"

- ChangeLog
> Fix typo in ChangeLog

- src/gwsocket.c
- src/options.c
- src/settings.h
- src/websocket.c
- src/websocket.h
Implements UNIX-domain socket support as requested in #1662
> Implemented websocket server bind on unix-domain sockets

- src/khash.h
- src/pdjson.c
- src/util.c
Silence and fix unsigned overflows reported by clang's UBSAN.
> Resolve UBSAN issues

- README.md
> Update README regarding usage of GoAccess APT repository

- goaccess.1
Since many seem to struggle on how to use the WebSocket, I added some extra note to manpage. 
Hopefully this will help to understand how it works.
> Added more details about WebSocket server to manpage

- resources/css/app.css
> Fix visualization issue for panels with disabled chart

- src/browsers.c
Here's a small PR with some useragents I found in my logs, I looked up what they were and put them in the correct categories.
> Add more useragents!

- src/websocket.c
> Fix support for OpenSSL < 1.1.0

- src/goaccess.c
As discussed in https://github.com/allinurl/goaccess/issues/2283
> Change stderr to stdout on non-error output

- src/gholder.c
- src/gholder.h
- src/options.c
- src/settings.h
Hello, this is an attempt to address #2282. This is heavily inspired from the discussion there.
| Bits hidden | level 1 | level 2 | level 3 |
| - | - | - | - |
| IPv4 | 8 | 16 | 24 |
| IPv6 | 64 | 80 | 96 |
> New --anonymize-level option

- po/ru.po
- po/uk.po
> Update Russian and Ukrainian translations

- README.md
See https://github.com/allinurl/goaccess/issues/2321#issuecomment-1129074851
> Include arch in ubuntu/debian repo instructions

- po/LINGUAS
- po/ko.po
I just discovered goaccess yesterday and saw that no one seems to have done Korean i18n yet.
I hope this helps.
> Korean PO file added

- goaccess.1
- src/parser.c
> Nanosecond parsing option. 

- .github/workflows/docker-publish.yml
> Modernize Docker login

- .codespellrc
- .github/workflows/spelling.yml
> Add spell checking workflow

- config/browsers.list
Let me add two crawlers; SeznamBot and AppleBot.
- SeznamBot https://napoveda.seznam.cz/en/seznambot-crawler/
- AppleBot https://support.apple.com/en-us/HT204683
> Add SeznamBot, AppleBot as Crawlers

- src/gkhash.c
Free the duplicated key in inc_su64() on failure.
Use the same pattern as in inc_su64() for inc_si32(), by duplicating the key after an empty lookup result. This simplifies the call sites ht_inc_cnt_overall() and ht_ins_seq() by avoiding a duplicate lookup.
> Update hash table increment functions

- src/output.c
> Add `theme-color` `<meta>` tag
